- name: Laravel Pint
  # You may pin to the exact commit or the version.
  # uses: aglipanci/laravel-pint-action@94b4f43fc38663bc80af4b2bdde1a63b1bdbcb05
  uses: aglipanci/laravel-pint-action@0.1.0
  with:
    # would you like to run Pint on test mode
    testMode: # optional
    # would you like to run Pint on verbose mode
    verboseMode: # optional
    # specify the custom config path
    configPath: # optional
    # pint preset
    preset: # optional
